config/routes.rb
Rails.application.routes.draw do
  config = Rails.application.config.baukis2

  constraints host: config[:staff][:host] do
    namespace :staff, path: config[:staff][:path] do
      root 'top#index'
      get 'login' => 'sessions#new', as: :login
      resource :session, only: %i[create destroy]
      resource :account, except: %i[new create destroy]
      resource :password, only: %i[show edit update]
      resources :customers
    end
  end

  constraints host: config[:admin][:host] do
    namespace :admin, path: config[:admin][:path] do
      root 'top#index'
      get 'login' => 'sessions#new', as: :login
      resource :session, only: %i[create destroy]
      resources :staff_members do
        resources :staff_events, only: %i[index]
      end
      resources :staff_events, only: %i[index]
    end
  end

  constraints host: config[:customer][:host] do
    namespace :customer, path: config[:customer][:path] do
      root 'top#index'
    end
  end
end

app/models/staff_member.rb
class StaffMember < ApplicationRecord
  include EmailHolder
  include PersonalNameHolder
  include PasswordHolder

  has_many :events, class_name: 'StaffEvent', dependent: :destroy

  validates :start_date, presence: true, date: {
    after_or_equal_to: Date.new(2000, 1, 1),
    before: ->(_obj) { 1.year.from_now.to_date },
    allow_blank: true
  }
  validates :end_date, date: {
    after: :start_date,
    before: ->(_obj) { 1.year.from_now.to_date },
    allow_blank: true
  }

  def active?
    !suspended? && start_date <= Date.today && (end_date.nil? || end_date > Date.today)
  end
end

app/controllers/admin/staff_members_controller.rb
class Admin::StaffMembersController < Admin::Base
  def index
    @staff_members = StaffMember.order(:family_name_kana, :given_name_kana).page(params[:page])
  end

  def show
    staff_member = StaffMember.find(params[:id])
    redirect_to [:edit, :admin, staff_member]
  end

  def new
    @staff_member = StaffMember.new
  end

  def edit
    @staff_member = StaffMember.find(params[:id])
  end

  def create
    @staff_member = StaffMember.new(staff_members_params)
    if @staff_member.save
      flash.notice = '職員アカウントを新規登録しました。'
      redirect_to :admin_staff_members
    else
      render action: 'new'
    end
  end

  def update
    @staff_member = StaffMember.find(params[:id])
    @staff_member.assign_attributes(staff_members_params)
    if @staff_member.save
      flash.notice = '職員アカウントを更新しました。'
      redirect_to :admin_staff_members
    else
      render action: 'edit'
    end
  end

  def destroy
    staff_member = StaffMember.find(params[:id])
    staff_member.destroy!
    flash.notice = '職員アカウントを削除しました。'
    redirect_to :admin_staff_members
  end

  private

  def staff_members_params
    params.require(:staff_member).permit(
      :email,
      :password,
      :family_name,
      :given_name,
      :family_name_kana,
      :given_name_kana,
      :start_date,
      :end_date,
      :suspended
    )
  end
end

app/views/admin/staff_members/_form.html.erb
<% # app/presenters/staff_member_form_presenter.rbのStaffMemberFormPresenterクラスのプレゼンター %>
<%= markup do |m|
  p = StaffMemberFormPresenter.new(f, self)
  m << p.notes
  p.with_options(required: true) do |q|
    m << q.text_field_block(:email, "メールアドレス", size: 32)
    m << q.password_field_block(:password, "パスワード", size: 32)
    m << q.full_name_block(:family_name, :given_name, "氏名")
    m << q.full_name_block(:family_name_kana, :given_name_kana, "フリガナ")
    m << q.date_field_block(:start_date, "入社日")
    m << q.date_field_block(:end_date, "退職日", required: false)
  end
  m << p.suspended_checkbox
end %>

app/views/admin/staff_members/edit.html.erb
<% @title = "職員アカウントの編集" %>
<h1><%= @title %></h1>

<div id="generic-form">
    <%= form_with model: @staff_member, url: [ :admin, @staff_member ] do |f| %>
    <%= render "form", f: f %>
    <div class="buttons">
        <%= f.submit "更新" %>
        <%= link_to  "キャンセル", :admin_staff_members %>
    </div>
    <% end %>
</div>

app/views/admin/staff_members/index.html.erb
<% @title = "職員管理" %>
<h1><%= @title %></h1>

<div class="table-wrapper">
    <div class="links">
        <%= link_to "新規登録", :new_admin_staff_member %>
    </div>

    <%= paginate @staff_members %>

    <table class="listing">
        <tr>
            <th>氏名</th>
            <th>フリガナ</th>
            <th>メールアドレス</th>
            <th>入社日</th>
            <th>退職日</th>
            <th>停止フラグ</th>
            <th>アクション</th>
        </tr>
        <% @staff_members.each do |m| %>
        <% p = StaffMemberPresenter.new(m, self) %>
        <tr>
            <td><%= p.full_name %></td>
            <td><%= p.full_name_kana %></td>
            <td class="email"><%= m.email %></td>
            <td class="date"><%= m.start_date.strftime("%Y/%m/%d") %></td>
            <td class="date"><%= m.end_date.try(:strftime, "%Y/%m/%d") %></td>
            <td class="boolean"><%= p.suspended_mark %></td>
            <td class="actions">
                <%= link_to "編集", [ :edit, :admin, m ] %> |
                <%= link_to  "Events", [:admin, m, :staff_events] %> |
                <%# link_to  "Events", admin_staff_member_staff_events_path(m)とも書ける %>
                <%= button_to "削除", [ :admin, m ], method: :delete, data: { confirm: "本当に削除しますか？" } %>
            </td>
        </tr>
        <% end %>
    </table>

    <%= paginate @staff_members %>

    <div class="links">
        <%= link_to "新規登録", :new_admin_staff_member %>
    </div>
</div>

app/views/admin/staff_members/new.html.erb
<% @title = "職員の新規登録" %>
<h1><%= @title %></h1>

<div id="generic-form">
    <%= form_with model: @staff_member, url: [ :admin, @staff_member ] do |f| %>
    <%= render "form", f: f %>
    <div class="buttons">
        <%= f.submit "登録" %>
        <%= link_to  "キャンセル", :admin_staff_members %>
    </div>
    <% end %>
</div>